# Generated by Django 5.0.4 on 2024-10-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_publish_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('message', models.TextField(verbose_name='پیام')),
                ('subject', models.CharField(max_length=10, verbose_name='موضوع')),
            ],
        ),
    ]
