# Generated by Django 5.0.4 on 2024-12-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
    ]
