# Generated by Django 5.0.4 on 2024-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-subject'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='تلفن'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['subject'], name='blog_ticket_subject_2e04e6_idx'),
        ),
    ]
